### ISSUE TITLE
Script may come out of whack.

### ISSUE THREAD

**Issue by S4enL0ng** [Spikeone/RttR_Campaigns#14]
Hi Guys,
in Mission 1 of the old Roman Campaign the lua Script may stop functioning if you start looking for resources before you built (and a soldier occupied) the barracks. The Well would be okay, but any new ressources dont work and your stuck... because the barracks got deactivated again, also.
In the original Settlers2 Campaign, this doesn't happen because the order of execution may be irrelevant, But you may have non-linear timestamps in the message... But to be fair... i never really looked at it close enough to see it.
The same Problem may be the case on other maps too. Have not looked at it close enough yet.

I'm not comfortable enough to look at it in the moment, though.

**Comment by Spikeone** [comment]
Will have a look at this. The original could be broken as well, for instance I never unlocked most farming buildings in the original game so I will just make the script "working".
